export const GOVERNORATES = [
  { fr: 'Tunis', ar: 'تونس' },
  { fr: 'Ariana', ar: 'أريانة' },
  { fr: 'Ben Arous', ar: 'بن عروس' },
  { fr: 'Manouba', ar: 'منوبة' },
  { fr: 'Nabeul', ar: 'نابل' },
  { fr: 'Zaghouan', ar: 'زغوان' },
  { fr: 'Bizerte', ar: 'بنزرت' },
  { fr: 'Béja', ar: 'باجة' },
  { fr: 'Jendouba', ar: 'جندوبة' },
  { fr: 'Le Kef', ar: 'الكاف' },
  { fr: 'Siliana', ar: 'سليانة' },
  { fr: 'Sousse', ar: 'سوسة' },
  { fr: 'Monastir', ar: 'المنستير' },
  { fr: 'Mahdia', ar: 'المهدية' },
  { fr: 'Sfax', ar: 'صفاقس' },
  { fr: 'Kairouan', ar: 'القيروان' },
  { fr: 'Kasserine', ar: 'القصرين' },
  { fr: 'Sidi Bouzid', ar: 'سيدي بوزيد' },
  { fr: 'Gabès', ar: 'قابس' },
  { fr: 'Médenine', ar: 'مدنين' },
  { fr: 'Tataouine', ar: 'تطاوين' },
  { fr: 'Gafsa', ar: 'قفصة' },
  { fr: 'Tozeur', ar: 'توزر' },
  { fr: 'Kébili', ar: 'قبلي' },
]

export const CATS = ['face', 'eyes', 'lips', 'nails', 'skincare', 'accessories']

export const CATEGORY_META = {
  face: {
    fr: { hero: 'Maquillage Visage', sub: 'Fond de teint, blush, bronzer, correcteur et plus.' },
    ar: { hero: 'مكياج الوجه', sub: 'كريم أساس، أحمر خدود، برونزر وأكثر.' },
  },
  eyes: {
    fr: { hero: 'Maquillage Yeux', sub: 'Mascara, eyeliner, fards à paupières pour un regard intense.' },
    ar: { hero: 'مكياج العيون', sub: 'ماسكارا، آيلاينر وظلال عيون.' },
  },
  lips: {
    fr: { hero: 'Maquillage Lèvres', sub: 'Rouges à lèvres, gloss, lip liner pour des lèvres parfaites.' },
    ar: { hero: 'مكياج الشفاه', sub: 'أحمر شفاه، غلوس وقلم تحديد.' },
  },
  nails: {
    fr: { hero: 'Soin & Couleur Ongles', sub: 'Vernis, base coat, top coat pour des ongles impeccables.' },
    ar: { hero: 'العناية بالأظافر', sub: 'طلاء أظافر وطبقات عناية.' },
  },
  skincare: {
    fr: { hero: 'Soins de la Peau', sub: 'Crèmes, nettoyants, parfums pour prendre soin de vous.' },
    ar: { hero: 'العناية بالبشرة', sub: 'كريمات ومنظفات وعطور للعناية بجمالك.' },
  },
  accessories: {
    fr: { hero: 'Accessoires Beauté', sub: 'Pinceaux, recourbe-cils et tous vos essentiels beauté.' },
    ar: { hero: 'إكسسوارات الجمال', sub: 'فرش مكياج وكل أدوات الجمال الأساسية.' },
  },
}

export const T = {
  fr: {
    addToCart: 'Ajouter au panier',
    addedSuccess: 'Ajouté',
    buyNow: 'Acheter maintenant',
    outOfStock: 'Rupture de stock',
    shade: 'Teinte',
    chooseShade: 'Choisir une teinte',
    shadeRequired: 'Choisissez une teinte avant d\'ajouter au panier',
    reference: 'Référence',
    viewDetails: 'Voir détails',
    description: 'Description',
    backToProducts: 'Retour aux produits',
    cart: 'Panier',
    checkout: 'Commander',
    emptyCart: 'Votre panier est vide',
    orderSummary: 'Récapitulatif',
    total: 'Total',
    delivery: 'Livraison',
    free: 'Gratuite',
    cod: 'Paiement à la livraison',
    placeOrder: 'Passer la commande',
    fullName: 'Nom complet',
    phone: 'Téléphone',
    governorate: 'Gouvernorat',
    city: 'Ville',
    address: 'Adresse complète',
    required: 'Champ obligatoire',
    orderSuccess: 'Commande confirmée!',
    orderSuccessMsg: 'Votre commande a été reçue. Notre équipe vous contactera sous 24h pour confirmation.',
    admin: 'Admin',
    orders: 'Commandes',
    products: 'Produits',
    backToShop: 'Retour boutique',
    pending: 'En attente',
    confirmed: 'Confirmée',
    delivered: 'Livrée',
    cancelled: 'Annulée',
    search: 'Rechercher...',
    sortBy: 'Trier par',
    priceAsc: 'Prix croissant',
    priceDesc: 'Prix décroissant',
    items: 'produit(s)',
    noOrders: 'Aucune commande',
    noProducts: 'Aucun produit',
    markConfirmed: 'Confirmer',
    markDelivered: 'Livrée',
    tnd: 'DT',
    customerInfo: 'Client',
    orderId: 'Commande #',
    revenue: 'Revenus',
    all: 'Tous',
    password: 'Mot de passe',
    loginBtn: 'Accéder',
    wrongPassword: 'Mot de passe incorrect',
    adminTitle: 'Tableau de bord',
    logout: 'Déconnexion',
    productNameFr: 'Nom FR',
    productNameAr: 'Nom AR',
    category: 'Catégorie',
    price: 'Prix',
    stock: 'Stock',
    imageUrl: 'Image URL',
    uploadImage: 'Uploader image',
    saveProduct: 'Enregistrer produit',
    newProduct: 'Nouveau produit',
    editProduct: 'Modifier',
    deleteProduct: 'Supprimer',
    active: 'Actif',
    inactive: 'Inactif',
    tag: 'Badge',
    variants: 'Teintes',
    addVariant: 'Ajouter une teinte',
    editVariant: 'Modifier teinte',
    saveVariant: 'Enregistrer teinte',
    deleteVariant: 'Supprimer teinte',
    variantImage: 'Image teinte',
    variantPrice: 'Prix teinte optionnel',
    colorHex: 'Couleur HEX',
    basePrice: 'Prix produit',
    salePrice: 'Prix final',
    loadError: 'Impossible de charger les données.',
    catLabels: {
      face: 'Visage',
      eyes: 'Yeux',
      lips: 'Lèvres',
      nails: 'Ongles',
      skincare: 'Soins',
      accessories: 'Accessoires',
    },
  },
  ar: {
    addToCart: 'أضف إلى السلة',
    addedSuccess: 'تمت الإضافة',
    buyNow: 'اشتري الآن',
    outOfStock: 'غير متوفر',
    shade: 'اللون',
    chooseShade: 'اختاري اللون',
    shadeRequired: 'اختاري اللون قبل إضافة المنتج',
    reference: 'المرجع',
    viewDetails: 'عرض التفاصيل',
    description: 'الوصف',
    backToProducts: 'العودة للمنتجات',
    cart: 'السلة',
    checkout: 'إتمام الطلب',
    emptyCart: 'سلتك فارغة',
    orderSummary: 'ملخص الطلب',
    total: 'المجموع',
    delivery: 'التوصيل',
    free: 'مجاني',
    cod: 'الدفع عند الاستلام',
    placeOrder: 'تأكيد الطلب',
    fullName: 'الاسم الكامل',
    phone: 'رقم الهاتف',
    governorate: 'الولاية',
    city: 'المدينة',
    address: 'العنوان الكامل',
    required: 'هذا الحقل مطلوب',
    orderSuccess: 'تم تأكيد طلبك!',
    orderSuccessMsg: 'تم استلام طلبك. سيتواصل معك فريقنا خلال 24 ساعة للتأكيد.',
    admin: 'الإدارة',
    orders: 'الطلبات',
    products: 'المنتجات',
    backToShop: 'العودة للمتجر',
    pending: 'قيد الانتظار',
    confirmed: 'مؤكد',
    delivered: 'تم التوصيل',
    cancelled: 'ملغى',
    search: 'ابحث...',
    sortBy: 'ترتيب',
    priceAsc: 'السعر تصاعدي',
    priceDesc: 'السعر تنازلي',
    items: 'منتج',
    noOrders: 'لا توجد طلبات',
    noProducts: 'لا توجد منتجات',
    markConfirmed: 'تأكيد',
    markDelivered: 'تسليم',
    tnd: 'د.ت',
    customerInfo: 'العميل',
    orderId: 'طلب #',
    revenue: 'الإيرادات',
    all: 'الكل',
    password: 'كلمة المرور',
    loginBtn: 'دخول',
    wrongPassword: 'كلمة المرور غير صحيحة',
    adminTitle: 'لوحة التحكم',
    logout: 'خروج',
    productNameFr: 'الاسم بالفرنسية',
    productNameAr: 'الاسم بالعربية',
    category: 'الفئة',
    price: 'السعر',
    stock: 'المخزون',
    imageUrl: 'رابط الصورة',
    uploadImage: 'رفع صورة',
    saveProduct: 'حفظ المنتج',
    newProduct: 'منتج جديد',
    editProduct: 'تعديل',
    deleteProduct: 'حذف',
    active: 'نشط',
    inactive: 'غير نشط',
    tag: 'شارة',
    variants: 'الألوان',
    addVariant: 'إضافة لون',
    editVariant: 'تعديل لون',
    saveVariant: 'حفظ اللون',
    deleteVariant: 'حذف اللون',
    variantImage: 'صورة اللون',
    variantPrice: 'سعر اللون اختياري',
    colorHex: 'كود اللون',
    basePrice: 'السعر الأساسي',
    salePrice: 'السعر النهائي',
    loadError: 'تعذر تحميل البيانات.',
    catLabels: {
      face: 'الوجه',
      eyes: 'العيون',
      lips: 'الشفاه',
      nails: 'الأظافر',
      skincare: 'العناية',
      accessories: 'إكسسوارات',
    },
  },
}

export const getName = (p, lang) => {
  if (!p) return ''
  if (lang === 'ar') return p.nameAr || p.name_ar || p.nameFr || p.name_fr || ''
  return p.nameFr || p.name_fr || p.nameAr || p.name_ar || ''
}

export const fmt = (price, tnd) => `${Number(price || 0).toFixed(3).replace('.', ',')} ${tnd}`
